### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by uduse** [aimhubio/aim#1416]
## 🐛 Bug
Can't load my `metrics` screen because this problem:

```python
 File ".../aim/web/api/runs/object_api_utils.py", line 91, in set_ranges
    step = (self.index_range.stop - self.index_range.start) // index_density or 1
ZeroDivisionError: integer division or modulo by zero
```

- Aim Version (e.g., 3.0.1)
```
aim==3.6.1
aimrecords==0.0.7
aimrocks==0.0.10
```
- Python version: 3.8
- pip version: 22.0.3
- OS (e.g., Linux): Linux

**Comment by roubkar** [comment]
Hey @uduse, thanks for reporting this issue.
We're exploring this now and will get back to you asap.

**Comment by alberttorosyan** [comment]
Hi @uduse! We just released aim `v3.6.2` with fix for `ZeroDivisionError` 🎉 
It covers both UI and API, and disallows to set 0 as step/record count. Please give it a try.

**Comment by uduse** [comment]
> Hi @uduse! We just released aim `v3.6.2` with fix for `ZeroDivisionError` 🎉 It covers both UI and API, and disallows to set 0 as step/record count. Please give it a try.

Oh that's why my metrics aren't showing lol. It seemed to me Aim is kinda unfriendly for single scalar metrics. Each run of my program outputs a couple scalar metrics without steps, and it's kinda hard to compare them in aim.

**Comment by uduse** [comment]
Previously `Runs > Texts` aren't showing results correctly and now it does. However, I'm still unable to open the metrics menu for some reason. In my case I only track two metrics with 0 step (so two scalar values for each run). I think maybe you should have more tests for cases where only one step data is added? 🤔

**Comment by uduse** [comment]
This is what happens when I click on `Metrics`
![image](https://user-images.githubusercontent.com/4717005/157099311-8e1ba977-a37e-45fc-b586-a138e4262cb0.png)

**Comment by alberttorosyan** [comment]
Hi @uduse! Sorry to hear you're still experiencing issues with running Aim.
The metrics are handled in a different way from the objects, and the code-base for those is separate. May I ask you to open a new issue for that one?
And just to double-check, tracking two metrics with only one step each (`0`) should be enough to reproduce?
Thanks in advance!

**Comment by uduse** [comment]
It's hard for me to reduce to a version where my metrics view doesn't work, but yes doing that should be a good starting point.

**Comment by gorarakelyan** [comment]
Closing this issue, as `zeroDivisionError` has been fixed. @uduse please feel free to fire a new issue(if there is any) with reproduction steps, so we could debug and resolve it. Would be happy to help in any way we can.
