### ISSUE TITLE
Cannot visualize run in UI when a tag is added

### ISSUE THREAD

**Issue by fg91** [aimhubio/aim#2267]
## 🐛 Bug

When running a remote tracking server (v3.14.0) and adding a tag via `run.add_tag("foo")`, I get the following error:

```console
pydantic.error_wrappers.ValidationError: 2 validation errors for RunInfoOut
response -> props -> tags -> 0 -> color
  none is not an allowed value (type=type_error.none.not_allowed)
response -> props -> tags -> 0 -> description
  none is not an allowed value (type=type_error.none.not_allowed)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 405, in run_asgi
    self.scope, self.receive, self.send
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 390, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 18, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 35, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 236, in app
    is_coroutine=is_coroutine,
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 130, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 2 validation errors for RunInfoOut
response -> props -> tags -> 0 -> color
  none is not an allowed value (type=type_error.none.not_allowed)
response -> props -> tags -> 0 -> description
  none is not an allowed value (type=type_error.none.not_allowed)
```

<img width="1420" alt="Screenshot 2022-10-11 at 10 15 45" src="https://user-images.githubusercontent.com/36511035/195037051-82fe1d5c-4e3c-47dd-85b3-2f5fb463042c.png">

### Environment

- Aim Version 3.14.0
- Python version 3.7.14
- pip version
- OS Docker image built on python:3.7
- Any other relevant information

**Comment by alberttorosyan** [comment]
Hey @fg91! Thanks for reporting the issue. Looking into it.

**Comment by m-toman** [comment]
Just wanted to chime in saying that I also encountered this when doing add_tag in 3.14.1

Looks like this, when I comment the add_tag it works for this run.
```
            import aim
            run_name = f"{experiment_name}-acoustic"
            self.aim_run = aim.Run(run_hash=run_name,
                                   repo=constants.AIM_URI,
                                   experiment=experiment_name,
                                   log_system_params=True)
            self.aim_run['hparams'] = hparams.as_dict()
            #self.aim_run.add_tag("acoustic")
```

For runs where I do add_tag I get:

```
pydantic.error_wrappers.ValidationError: 2 validation errors for RunInfoOut
response -> props -> tags -> 0 -> color
  none is not an allowed value (type=type_error.none.not_allowed)
response -> props -> tags -> 0 -> description
  none is not an allowed value (type=type_error.none.not_allowed)
```

Perhaps relevant: I use a remote AIM server.

(BTW I love your work, switched from our previous solution in one day without issues)

**Comment by alberttorosyan** [comment]
Thanks for the info @m-toman, @fg91 🙌 

I checked and it seems the issue comes from the way Pydantic handles the optional fields while validating schema. May I ask you to share the results of
```pip show pydantic```

Thanks in advance!

**Comment by m-toman** [comment]
@alberttorosyan Here's mine
```
pip show pydantic
Name: pydantic
Version: 1.8.2
Summary: Data validation and settings management using python 3.6 type hinting
Home-page: https://github.com/samuelcolvin/pydantic
Author: Samuel Colvin
Author-email: s@muelcolvin.com
License: MIT
Location: /opt/conda/envs/pytorch/lib/python3.9/site-packages
Requires: typing-extensions
Required-by: fastapi, spacy, thinc
```

This is running on the AWS DeepLearning AMI, Ubuntu version

**Comment by Seraphli** [comment]
Any update about this issue? I'm still having this issue.

**Comment by mihran113** [comment]
Hey @Seraphli! Can I ask you what version of `aim` are you using?

**Comment by Seraphli** [comment]
@mihran113 v3.15.2

**Comment by mihran113** [comment]
@Seraphli Could you please provide some more details? As this should've been fixed with `3.14.2` release.

**Comment by Seraphli** [comment]
@mihran113 It has been a long time since I had this bug. I tried to delete `.aim` folder but the issue still persists. After that, I changed log utils to wandb. I tried to run the previous version code but I can not reproduce this bug now. I will leave a comment when I can reproduce it.
