### ISSUE TITLE
aim cannot be installed with python 3.12.3

### ISSUE THREAD

**Issue by KDanm** [aimhubio/aim#3159]
## 🐛 Bug

aim cannot be installed on python 3.12.3

### To reproduce

use "pip3 install aim" on a machine with Python 3.12.3 because "No matching distribution found for aimrocks==0.4.0"
full error:
ERROR: Could not find a version that satisfies the requirement aimrocks==0.4.0 (from versions: 0.2.0, 0.5.2)
ERROR: No matching distribution found for aimrocks==0.4.0
(ultra) danielk@gpu-t4-4:~/project/momentick-train/train$ pip install aim==3.20.1
Collecting aim==3.20.1
  Using cached aim-3.20.1.tar.gz (1.6 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Collecting setuptools
        Using cached setuptools-70.0.0-py3-none-any.whl.metadata (5.9 kB)
      Collecting cython==3.0.0a11
        Using cached Cython-3.0.0a11-py2.py3-none-any.whl.metadata (2.7 kB)
      ERROR: Could not find a version that satisfies the requirement aimrocks==0.4.0 (from versions: 0.2.0, 0.5.2)
      ERROR: No matching distribution found for aimrocks==0.4.0
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

### Expected behavior

I expected aim to support python 3.12
### Environment

- Aim Version (e.g., 3.0.1)
- Python version 3.12
- pip version pip 24.0
- OS (e.g., Linux) Debian
- Any other relevant information

**Comment by mihran113** [comment]
Hey @KDanm! Thanks a lot for the report. We've already addressed this and python 3.12 will be supported with the upcoming version of the aim (`3.21.0`). In the meantime you can use this dev release: 
```
pip install aim==3.21.0.dev3
```

**Comment by tatyusha** [comment]
Hey @KDanm! In case you missed, Aim v3.21 is already shipped 🎉 
https://github.com/aimhubio/aim/releases/tag/v3.21.0

**Comment by ywlmiysm** [comment]
@tatyusha still exists
use "pip3 install aim==3.24.0" on a machine with Python 3.12.5 because "No matching distribution found for aimrocks==0.5.0"
full error:
      ERROR: Could not find a version that satisfies the requirement aimrocks==0.5.* (from versions: 0.2.0)
      ERROR: No matching distribution found for aimrocks==0.5.*

**Comment by ywlmiysm** [comment]
@tatyusha still exists
use "pip3 install aim==3.24.0" on a machine with Python 3.12.5 because "No matching distribution found for aimrocks==0.5.0"
full error:
      ERROR: Could not find a version that satisfies the requirement aimrocks==0.5.* (from versions: 0.2.0)
      ERROR: No matching distribution found for aimrocks==0.5.*

**Comment by ywlmiysm** [comment]
Hey @tatyusha still exists
use "pip3 install aim==3.24.0" on a machine with Python 3.12.5 because "No matching distribution found for aimrocks==0.5.0"
full error:
      ERROR: Could not find a version that satisfies the requirement aimrocks==0.5.* (from versions: 0.2.0)
      ERROR: No matching distribution found for aimrocks==0.5.*

**Comment by mihran113** [comment]
Hey @ywlmiysm! Thanks for reaching out, could you please share the OS version of your machine?

**Comment by ayushrjc** [comment]
**Hi @mihran113, having same error!!**

_Collecting aim-mlflow
  Using cached aim_mlflow-0.2.1-py3-none-any.whl.metadata (3.4 kB)
Collecting aim (from aim-mlflow)
  Using cached aim-3.24.0.tar.gz (1.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Collecting setuptools
        Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
      Collecting cython==3.0.10
        Using cached Cython-3.0.10-cp312-cp312-win_amd64.whl.metadata (3.2 kB)
      ERROR: Could not find a version that satisfies the requirement aimrocks==0.5.* (from versions: 0.2.0)
      ERROR: No matching distribution found for aimrocks==0.5.*
      [end of output]_

**python version - 3.12.6**

**Comment by ryanJigo** [comment]
Hey @mihran113. I have the same issue. python == 3.12.7

Collecting aim==3.25.0 (from -r requirements.txt (line 1))
  Downloading aim-3.25.0.tar.gz (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 4.9 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Collecting setuptools
        Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
      Collecting cython==3.0.10
        Downloading Cython-3.0.10-cp312-cp312-win_amd64.whl.metadata (3.2 kB)
      ERROR: Could not find a version that satisfies the requirement aimrocks==0.5.* (from versions: 0.2.0)
      ERROR: No matching distribution found for aimrocks==0.5.*
      [end of output]

**Comment by ywlmiysm** [comment]
> Hey @ywlmiysm! Thanks for reaching out, could you please share the OS version of your machine?

Windows 11 Home

(.venv) PS F:\ai\Transformer-from-scratch> pip install aim -i https://mirrors.aliyun.com/pypi/simple/     
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting aim
  Downloading https://mirrors.aliyun.com/pypi/packages/2a/90/9ce775b09addb233ca199aa28d41fadedac57f9691bb688b30894356e6be/aim-3.25.0.tar.gz (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 8.1 MB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
      Collecting setuptools
        Using cached https://mirrors.aliyun.com/pypi/packages/ff/ae/f19306b5a221f6a436d8f2238d5b80925004093fa3edea59835b514d9057/setuptools-75.1.0-py3-none-any.whl (1.2 MB)
      Collecting cython==3.0.10
        Downloading https://mirrors.aliyun.com/pypi/packages/2f/59/6669edfd1fad83ee18d698b897f25871b5296e258f74964a003d50d003fe/Cython-3.0.10-cp312-cp312-win_amd64.whl (2.8 MB)
           ---------------------------------------- 2.8/2.8 MB 8.1 MB/s eta 0:00:00
      ERROR: Could not find a version that satisfies the requirement aimrocks==0.5.* (from versions: 0.2.0)
      ERROR: No matching distribution found for aimrocks==0.5.*
      [end of output]

**Comment by HarikrishnanBalagopal** [comment]
Facing the same issue on MacOS with `Python 3.13.1`

**Comment by mihran113** [comment]
Hey @HarikrishnanBalagopal! Sorry, we don't have support for python 13 added yet. Will ping here, once added :)

**Comment by mihran113** [comment]
@ayushrjc @ryanJigo Sorry for the late response, I've somehow lost track of this issue. Could you please specify the OS version you are using? Because we have wheels for `aimrocks` for python 3.12 and for multiple linux and OSX versions. And apparently that's the issue that you are facing.

**Comment by mihran113** [comment]
Hey @ywlmiysm. Sorry, but we don't have support for windows devices unfortunately.

**Comment by gkanwar** [comment]
Hi @mihran113 , any word on support for Python 3.13? I'm getting the same issue attempting to install in an environment with Python 3.13.7. Thanks in advance!
